import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "../styles/globals.css";
import { NavigationProvider } from "../contexts/NavigationContext";
import { Header } from "../components/common/Header";
import { BottomNavigation } from "../components/common/BottomNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const pretendard = localFont({
  src: [
    {
      path: "../node_modules/pretendard/dist/web/static/woff2/Pretendard-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../node_modules/pretendard/dist/web/static/woff2/Pretendard-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../node_modules/pretendard/dist/web/static/woff2/Pretendard-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${pretendard.variable} antialiased`}
      >
        <NavigationProvider>
          <div
            className="flex flex-col h-screen items-start relative bg-white mx-auto"
            style={{ width: "var(--app-width)" }}
          >
            {/* Fixed Header */}
            <div
              className="fixed top-0 left-1/2 -translate-x-1/2 z-50"
              style={{ width: "var(--app-width)" }}
            >
              <Header />
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 w-full overflow-y-auto" style={{ paddingTop: "var(--header-height)", paddingBottom: "var(--footer-height)" }}>
              {children}
            </div>

            {/* Fixed Bottom Navigation */}
            <div
              className="fixed bottom-0 left-1/2 -translate-x-1/2 z-50"
              style={{ width: "var(--app-width)" }}
            >
              <BottomNavigation />
            </div>
          </div>
        </NavigationProvider>
      </body>
    </html>
  );
}
